Initial refund functionality
nofrixion/nofrixion.webcomponents pull request #106
Opened 2023-08-01 17:25 UTC by sauravmaiti22

- Added refund modal which supports partial refunds.
- If the card is authorised but not captured, partial refund is not possible.
- Added a paymentAttemptsHelper.ts which contains calculations in a common place instead of scattered everywhere.
- Have tested a few scenarios and needs further testing.
- WIP: Need API changes to support scenarios like partial capture and refund. For now, only try happy paths.

2023-08-02 08:05 UTC, donalnofrixion approved these changes

2023-08-02 14:59 UTC, Publicker commented on src/components/ui/CardRefundModal/CardRefundModal.tsx
> +  IsPartialRefundPossible: boolean;
Starting a variable with uppercase should be reserved only for components

2023-08-02 20:13 UTC, agranillonf approved these changes

2023-08-04 16:35 UTC, sipsorcery approved these changes

2023-08-08 09:53 UTC, pabloi-nf requested changes
The icon should be smaller. It's in 16px, and it should be in 12px.
<img width="242" alt="image" src="https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/0caff366-a488-474c-9e41-7dbb3455b130">
<img width="208" alt="image" src="https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/9f64ee6c-b5b2-48ef-a979-59ccb0044aa1">

2023-08-08 11:56 UTC, pabloi-nf approved these changes

2023-08-08 12:03 UTC, merged