[MOOV-1989]: Added warning when only enabling wallet payments
nofrixion/nofrixion.webcomponents pull request #110
Opened 2023-08-03 00:37 UTC by agranillonf

When creating a payment request, if the user only enables Apple Pay / Google Pay, a warning telling them to make sure their users are able to use those platforms is shown under the payment methods.

2023-08-03 07:50 UTC, donalnofrixion approved these changes

2023-08-03 08:47 UTC, Publicker approved these changes

2023-08-03 09:31 UTC, pabloi-nf requested changes
Works perfect.
Let's update the text to:
"Do your customers have access to Apple Pay or Google Pay? If you are unsure, you may want to consider adding a second payment method as a backup."

2023-08-04 14:04 UTC, pabloi-nf approved these changes

2023-08-04 14:07 UTC, merged