Feature/moov 1597 payment request dashboard
nofrixion/nofrixion.webcomponents pull request #20
Opened 2023-03-31 15:58 UTC by donalnofrixion

2023-03-31 16:18 UTC, sipsorcery commented
If there's 0 matches on a filter type the tabbing doesn't work. In the below example the last tab selected was "Partially Paid"

![image](https://user-images.githubusercontent.com/197660/229175163-52972cef-c229-4797-850f-034e2197d11b.png)

2023-03-31 16:21 UTC, donalnofrixion commented
> If there's 0 matches on a filter type the tabbing doesn't work. In the below example the last tab selected was "Partially Paid"
> 
> ![image](https://user-images.githubusercontent.com/197660/229175163-52972cef-c229-4797-850f-034e2197d11b.png)

The PR is not quite ready yet 😀 I thought I didn’t add any reviewers

2023-04-03 13:52 UTC, donalnofrixion commented
Currently can be tested in StoryBook under `Functional/PaymentrequestDashboard`.

The following token can be used to test against sandbox. It contains lots of PaymentRequests in various states.

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbmlkIjoiMTZjOGZjM2YtMjc2MC00NjE2LWIzMWUtZTljMzQwOWNkMDA3In0.yO1KpQNcti6ffBgBiBydSy4BIYlwTbo6Nd1x91aZzTI`

2023-04-03 14:02 UTC, Publicker commented on src/components/ui/PaymentRequestDashboard/Tabs.css
> +}
If Tailwind was used in the component, we shouldn't need these classes.

2023-04-03 14:04 UTC, Publicker commented on src/components/ui/PrimaryButton/PrimaryButton.tsx
> +    <span
If we are rendering a button I'd suggest to use the `<button>` tag.

Regarding the UI, if we add the `transition` class, the hover transition would be a bit smoother.

2023-04-03 14:06 UTC, Publicker commented on src/web-components/PaymentRequestDashboard/PaymentRequestDashboard.tsx
We use to add the `Web` prefix in these kind of files.

2023-04-03 14:14 UTC, Publicker commented on src/components/ui/PaymentRequestDashboard/Tabs.css
> +  pointer-events: none;
I'll also add `cursor: not-allowed;` so you'd get a nice OS mouse distinction.

2023-04-03 14:14 UTC, Publicker commented on src/components/ui/PaymentRequestDashboard/Tabs.css
> +  pointer-events: none;
Here's the Tailwind documentation for it so you can see it: https://tailwindcss.com/docs/cursor

2023-04-04 10:47 UTC, pabloi-nf requested changes
Thanks Donal, looking good.

About the top row:
- The main title "Payment requests needs to have only 16px left margin from the tab. Now has 48px.
- The main greenish button should have a right margin of 24px.
- The "settings" button should also have a background like the other one. On the default state should be transparent, and on hover should be #EDF2F7.

<img width="182" alt="image" src="https://user-images.githubusercontent.com/127946572/229768808-ce900570-ca98-47aa-8728-5a6aaf28cc3e.png">


About the tabs:
- They need to have a different background color on the hover state. This color is #F0F2F5.
- This is not on the Figma, but I think the border top color of each tab can match the little dot color. That is: gray for the unpaid, orange for the partial and green for the paid.

Thanks

2023-04-04 12:52 UTC, donalnofrixion commented
Hi @pabloi-nf I've made the changes you requested.

2023-04-04 14:39 UTC, pabloi-nf requested changes
Thanks Donal, it looks great.
There's one thing that I missed. The font-weight of the "settings" button is set at 500. I know is the weight in the Figma file, but it looks much more bold on the HTML.
Can we change it to 400? After that it's ready.

Thank you very much

2023-04-04 15:05 UTC, pabloi-nf approved these changes

2023-04-04 15:48 UTC, merged