Add Edit Option Card component
nofrixion/nofrixion.webcomponents pull request #22
Opened 2023-04-17 09:02 UTC by Publicker

This pull request introduces the "Edit Option Card" component, designed for use on the Create Payment Request Page. The Option Card receives a label, value, and onClick callback as props, allowing it to be extended for various functionalities.

Link to check the component: https://6410c09a16b1ae3112580b1c-cbluijcojs.chromatic.com/?path=/story/ui-edit-option-card--payment-conditions

2023-04-17 09:07 UTC, donalnofrixion approved these changes

2023-04-17 09:16 UTC, arifmatin approved these changes

2023-04-20 08:43 UTC, Publicker commented
@pabloi-nf I've addressed the changes you requested. Please take a look when you have some time.

What's new:

- Added a hover effect for the Edit icon
- Included a description beneath the card

---

Check out this video for a quick demo:

https://user-images.githubusercontent.com/52673485/233310268-6e9353c3-62a3-4da1-819f-fadfdbf2e2d4.mp4

2023-04-21 08:59 UTC, pabloi-nf requested changes
A few comments:

- It looks like the whole card is clickable. Let's do only the icon to be clickable.
- The settings text size should be 12px, and the line-heigth 16px

2023-04-21 10:57 UTC, Publicker commented
@pabloi-nf I've made the changes you requested, and they're all set for you to review.

2023-04-21 12:25 UTC, pabloi-nf approved these changes

2023-04-21 12:27 UTC, merged