Add "Available Methods Modal" and supporting components
nofrixion/nofrixion.webcomponents pull request #24
Opened 2023-04-19 16:03 UTC by Publicker

This pull request introduces the "Available Methods Modal," which will be used for configuring payment requests during creation. To implement this modal, several new components were developed:

- Checkbox
- CustomModal
- InfoTooltip
- Select
- Switch

Demo video showing all the components individually and all together in the Available Methods Modal:

https://user-images.githubusercontent.com/52673485/233133931-343ecf35-ba25-4f68-af8a-71a2195650cc.mp4

2023-04-19 16:23 UTC, donalnofrixion approved these changes

2023-04-20 07:59 UTC, pabloi-nf requested changes
Great work!

Some small adjustments:
- The distance between the checkbox and the label should be 12px 
<img width="69" alt="image" src="https://user-images.githubusercontent.com/127946572/233296564-52b6ee1e-1c9e-42bd-8728-a0994bce97f3.png">
- There is a difference between the bottom-margins in these 2 checkbox components. The preferred is the one under cards.  
<img width="416" alt="image" src="https://user-images.githubusercontent.com/127946572/233298976-430e84bc-749b-4773-9b0a-d4c07beeac60.png">
- The button needs a hover state with a transition.

https://user-images.githubusercontent.com/127946572/233299760-3e118423-f138-464a-8847-66ecb21b76b4.mov

2023-04-20 10:45 UTC, Publicker commented
@pabloi-nf I've made the changes you requested, and they're all set for you to review.

2023-04-21 10:55 UTC, Publicker commented
@pabloi-nf I've added the animation. Feel free to check it out whenever you get a chance.

2023-04-21 12:22 UTC, pabloi-nf approved these changes

2023-04-21 12:36 UTC, merged