Add "Use as my default" checkbox
nofrixion/nofrixion.webcomponents pull request #26
Opened 2023-04-21 14:48 UTC by Publicker

This pull request adds the "Use as my default" checkbox to the Available Methods Modal (and as flag for any other modal). The checkbox was not initially included due to a previous decision, but after a more in-depth discussion with Pablo I., it was decided to reintroduce it.

!["Use as my default" checkbox](https://user-images.githubusercontent.com/52673485/233666159-3f2be555-6e5a-412d-a322-326a08f70882.png)

2023-04-21 14:55 UTC, donalnofrixion approved these changes

2023-04-21 15:59 UTC, sipsorcery approved these changes

2023-04-24 10:35 UTC, pabloi-nf requested changes
Let's use 2rem for the left margin on the checkbox 
<img width="486" alt="image" src="https://user-images.githubusercontent.com/127946572/233972221-7c4c4b67-ff74-4ea6-bcdd-682ab552b49b.png">

2023-04-24 10:41 UTC, Publicker commented
> Let's use 2rem for the left margin on the checkbox <img alt="image" width="486" src="https://user-images.githubusercontent.com/127946572/233972221-7c4c4b67-ff74-4ea6-bcdd-682ab552b49b.png">

@pabloi-nf Done! Should be up now.

2023-04-24 11:37 UTC, pabloi-nf approved these changes

2023-04-24 13:03 UTC, merged