User payment defaults
nofrixion/nofrixion.webcomponents pull request #53
Opened 2023-05-30 11:58 UTC by donalnofrixion

2023-05-30 15:46 UTC, arifmatin approved these changes

2023-05-31 09:07 UTC, donalnofrixion commented
Hi @Publicker I've made those changes we discussed yesterday.

2023-06-01 07:27 UTC, Publicker requested changes

2023-06-01 07:27 UTC, Publicker commented on src/components/functional/CreatePaymentRequestPage/CreatePaymentRequestPage.tsx
> +  const getDefaultUserPaymentDefaults = (): UserPaymentDefaults => {
This could be rather just a variable, there's no need for a function. We'd even have this into a `constants` file.

2023-06-01 07:27 UTC, Publicker commented on src/components/ui/EditOptionCard/EditOptionCard.tsx
> +// TODO: Disable edit mode when isLoading is true
This seems to be already implemented.

2023-06-01 07:27 UTC, Publicker commented on src/components/ui/EditOptionCard/EditOptionCard.tsx
Could we add two Storybook stories, one for each `UI/Edit Option Card` that we have (that being `UI/Edit Option Card/Payment Conditions` and `UI/Edit Option Card/Payment Methods`) but in their respective loading state?

2023-06-01 08:28 UTC, merged