[MOOV-1864]: Added new Payment Request Dashboard filter controls
nofrixion/nofrixion.webcomponents pull request #74
Opened 2023-06-28 05:23 UTC by agranillonf

Added the ability to filter the payment request dashboard by:

- Text: On Merchant's name, payment request description and title, customer email address and PISP reference.
- Currency.
- Minimum requested amount.
- Maximum requested amount.
- Tags

The API client was also updated to support these filters.

2023-06-28 07:34 UTC, donalnofrixion commented
Looks awesome Axel! very cool. One small thing. Should the Tag filter have a clear 'X' similar to the amount filter?
![image](https://github.com/nofrixion/nofrixion.webcomponents/assets/89344328/b80c7879-5718-4392-acbb-ae5e2d2dc110)

2023-06-28 07:39 UTC, donalnofrixion requested changes

2023-06-28 07:39 UTC, donalnofrixion commented on src/components/ui/PaymentRequestAmountFilter/PaymentRequestAmountFilter.tsx
> +﻿import FilterButton from '../FilterButton/FilterButton';
I'd remove PaymentRequest from the name. We'll reuse these for Accounts Payable.

2023-06-28 07:39 UTC, donalnofrixion commented on src/components/ui/PaymentRequestTagFilter/PaymentRequestTagFilter.tsx
> +﻿import FilterButton from '../FilterButton/FilterButton';
Same here

2023-06-28 07:39 UTC, donalnofrixion commented on src/components/ui/PaymentRequestFilterRow/PaymentRequestFilterRow.tsx
> +﻿import DateRangePicker, { DateRange } from '../DateRangePicker/DateRangePicker';
Maybe here too?

2023-06-28 07:43 UTC, donalnofrixion commented
Selecting pounds in the amount filter doesn't seem to work.
![image](https://github.com/nofrixion/nofrixion.webcomponents/assets/89344328/cd027b7b-b605-4fbe-b8de-4d381ffbedd7)

2023-06-28 07:49 UTC, donalnofrixion commented
Should the tags be alphabetically ordered?
![image](https://github.com/nofrixion/nofrixion.webcomponents/assets/89344328/82f47044-ee7c-4149-b6bc-510dba3f16b9)

2023-06-28 09:26 UTC, pabloi-nf requested changes
Tags
- Tag cloud should be left aligned.
- Tag component buttons are missing the hover state.
- If the user clicks on "cancel" the tags selected should go back to the last state before opening the box. Video attached showing the problem. In the video you can see that I turned on 2 tags, clicked cancel, but when the dropdown is open again the tags are still selected, even when I didn't press on "Apply".
- Clicking outside the box should be the same as clicking "Cancel".
- Font-weight of the cancel button should be 400.

https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/ba5c88d2-a8b2-4a43-a935-002104ec22e3



Amount:
- The same cancel issue happens here.
- I made a mistake in the figma. The icon should be always the circle with the euro inside, not the filter icon.
- I find out it looks confusing if we don't put a border around the selected filter. We should do something like this 
<img width="285" alt="image" src="https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/8f22e501-7280-4b1c-a887-7d990501cb99">


Search:
- We should add an icon to reset the field. This can be an X like we have in the other ones.
<img width="258" alt="image" src="https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/6d2610c9-7668-4e34-85a3-78e1bbfce88b">


Thanks!

2023-06-28 15:10 UTC, agranillonf commented
> Looks awesome Axel! very cool. One small thing. Should the Tag filter have a clear 'X' similar to the amount filter? ![image](https://user-images.githubusercontent.com/89344328/249389374-b80c7879-5718-4392-acbb-ae5e2d2dc110.png)

@donalnofrixion There's no close button on the Figma, so I didn't put it in.

2023-06-28 15:11 UTC, agranillonf commented
> Selecting pounds in the amount filter doesn't seem to work. ![image](https://user-images.githubusercontent.com/89344328/249391637-cd027b7b-b605-4fbe-b8de-4d381ffbedd7.png)

@donalnofrixion It doesn't work because the necessary changes to the API haven't been deployed to develop as of this comment.

2023-06-28 18:48 UTC, agranillonf commented
All comments have been attended and the currency filter changes have been deployed to the DEV API.

2023-06-28 18:57 UTC, donalnofrixion approved these changes

2023-06-29 10:24 UTC, Publicker approved these changes

2023-06-29 10:42 UTC, pabloi-nf requested changes
Everything looks great! The only thing I'm seeing that I didn't notice before is that numbers don't have commas to separate thousands and millions 
<img width="236" alt="image" src="https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/b334a4a1-4855-4857-95f8-fb660513d9de">

2023-06-29 15:34 UTC, Publicker approved these changes

2023-06-29 16:04 UTC, pabloi-nf approved these changes

2023-06-29 16:04 UTC, Publicker commented
🎉 🎉 🎉

2023-06-29 16:05 UTC, donalnofrixion approved these changes

2023-06-29 16:06 UTC, merged