Update Responsiveness for PR Dashboard and PR Details
nofrixion/nofrixion.webcomponents pull request #85
Opened 2023-07-11 15:18 UTC by Publicker

This pull request includes modifications to the Payment Request dashboard and Payment Request page to enhance responsiveness. Please note that there are a few known areas for improvement that will be addressed in subsequent PRs. 

These include:

- The position of the 'Confirm PR' button in Review mode is not fixed to the bottom when the content is smaller than what it's inside.
- The tag manager currently defaults to a vertical orientation in mobile view, similar to the desktop view.
- The UI for date and sort filters in mobile view requires updates.

Any issues not listed above should be considered for feedback and future fixes.

Please review the changes and provide any necessary feedback.

2023-07-11 19:51 UTC, donalnofrixion approved these changes

2023-07-12 06:25 UTC, agranillonf approved these changes

2023-07-12 08:29 UTC, arifmatin approved these changes

2023-07-12 10:25 UTC, pabloi-nf requested changes
- Title font size should be 1.5 rem.
- There shouldn't be a scroll bar on the tabs.
<img width="355" alt="image" src="https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/d1a72f2b-5176-476e-8936-36c8ff891e21">
- Let's use 1.75rem for the tabs numbers font size.
- Let's change the contact name font weight to 400.
- The create payment request button should have 12px of padding top and bottom.
- The title and the content in the op ups is not aligned 
<img width="133" alt="image" src="https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/3bc37f13-be8a-4061-98e5-e522a4d26117">
- After creating a payment request, I can't scroll anymore on the list (I don't know if this is a problem with Storybook).
- The 3 dots should look like they have the same distance with the edge of the card and with the EUR text 
<img width="66" alt="image" src="https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/b64a6572-8201-4d05-aa51-d1cf90c05776">
- We should redesign the pager, it's too small to be used on mobile.
- I'm making new payment methods icons to adapt better to this size.

2023-07-12 11:02 UTC, Publicker commented
@pabloi-nf Most comment were addressed.

Those were:
- ✅ Title font size should be 1.5 rem.
- ✅ There shouldn't be a scroll bar on the tabs.
- ✅ Let's use 1.75rem for the tabs numbers font size.
- ✅ Let's change the contact name font weight to 400.
- ✅ The create payment request button should have 12px of padding top and bottom.
- ✅ The title and the content in the op ups is not aligned
- ✅ The 3 dots should look like they have the same distance with the edge of the card and with the EUR text

---
Will investigate over:
- 🧐 After creating a payment request, I can't scroll anymore on the list (I don't know if this is a problem with Storybook).

Will wait for designs for:
- 🎨 We should redesign the pager, it's too small to be used on mobile.
- 🎨 I'm making new payment methods icons to adapt better to this size.

2023-07-12 14:01 UTC, merged