[MOOV-1924]: Added Payment Request Attempt Capture
nofrixion/nofrixion.webcomponents pull request #86
Opened 2023-07-11 22:38 UTC by agranillonf

Added full and partial capture functionality to payment request transactions/attempts.

This PR requires an updated version of the MoneyMoov Client.

2023-07-12 09:45 UTC, Publicker approved these changes
Looks good - it'll get a bit tricker to one of us when merging, depending on which PR merges first, if this one or #85.

As loads files have been largely modified, particularly on classes.

2023-07-14 14:25 UTC, donalnofrixion approved these changes

2023-07-14 14:34 UTC, pabloi-nf requested changes
It doesn't matter which quantity I put, it displays 0.00 as the captured quantity. If I try to make another capture again, it tells me "bad request".
We should remove the button if no more capture is possible on this payment.

https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/3b8699e8-8a65-4f98-a2e6-58721ac2c9ff

2023-07-14 14:37 UTC, Publicker requested changes
All looking good, but found two things.

- The "Total payment was X.XX" label is align to the middle and seems a bit off, but that's just my opinion, maybe @pabloi-nf could have a better take in here
![Screenshot 2023-07-14 at 15 31 13](https://github.com/nofrixion/nofrixion.webcomponents/assets/52673485/5bd6dd33-b50e-41f9-aa5a-e93711f84074)

------

- Immediately after capturing, the modal closes and goes back to the PR Details, which is perfect, but it shows the captured value as "0", rather than the captured amount. Note: after reloading the page, it correctly shows the captured value.
![Screenshot 2023-07-14 at 15 31 32](https://github.com/nofrixion/nofrixion.webcomponents/assets/52673485/d8f92c33-5d70-4a37-aff6-9c517e5036b8)

2023-07-14 16:53 UTC, agranillonf commented
@pabloi-nf @Publicker The captured amount showing as 0 has been fixed.

2023-07-14 18:15 UTC, Publicker approved these changes

2023-07-18 16:06 UTC, pabloi-nf approved these changes

2023-07-19 01:29 UTC, agranillonf commented
Won't work until [MoneyMoov.Dotnet #160](https://github.com/nofrixion/moneymoov-dotnet/pull/160) and [NoFrixion.Clients #11](https://github.com/nofrixion/nofrixion.clients/pull/11) are merged, and a new version of the NoFrixion.Clients library (0.0.9) is released to NPM and referenced accordingly.

2023-07-19 09:19 UTC, sauravmaiti22 commented on src/utils/parsers.ts
> +            needsCapture:
To determine this we can check if AuthorizedAmount in attempt is greater than SettledAmount when payment method is card.

2023-07-19 20:03 UTC, agranillonf commented
Needs [MoneyMoov.Dotnet #163](https://github.com/nofrixion/moneymoov-dotnet/pull/163) merged to work.

2023-07-19 21:01 UTC, sauravmaiti22 approved these changes

2023-07-20 09:08 UTC, Publicker approved these changes

2023-07-20 13:54 UTC, merged